services:
  bot:
    image: ghcr.io/su-pr007/freesteamgamesparser-go:latest
    build:
      context: ./
      dockerfile: ./cmd/bot/Dockerfile
    restart: on-failure
    depends_on:
      - pg

  pg:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT_EXTERNAL}:5432'

volumes:
  postgres_data:

networks:
  default: